"""
Django settings for finalProyect project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4_o4926p6z34e#3e#=cgpc!pp_%lkry(1#dubwz#$25kk(9mdh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'restChifa.apps.RestchifaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finalProyect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finalProyect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

TIME_ZONE_USER = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NAME_PROYECT = 'restChifa'

# TIME OR DAYS IN THE FUTURE FROM NOW WHEN YOU CAN RESERVE
DAYS_IN_ADVANCE_RESERVES = 0
SECONDS_IN_ADVANCE_RESERVES = 3540 # 1 hour counting the minute

# LIMIT TIME OR DAYS IN THE FUTURE FROM NOW WHEN YOU CAN RESERVE
LIMIT_DAYS_IN_ADVANCE_RESERVES = 14
LIMIT_SECONDS_IN_ADVANCE_RESERVES = 0

# RANGE TIME RESERVES IN THE DAYS, IN UTC (UTC = SPAIN TIME - 2 HOURS AT LEAST THESE DAYS)
FIRST_HOUR_UTC_RESERVES = 10 # IN UTC (UTC = SPAIN TIME - 2 HOURS AT LEAST THESE DAYS)
FIRST_MINUTE_UTC_RESERVES = 00
LAST_HOUR_UTC_RESERVES = 21 # IN UTC (UTC = SPAIN TIME - 2 HOURS AT LEAST THESE DAYS)
LAST_MINUTE_UTC_RESERVES = 30

MAXIMUM_PEOPLE_PER_RESERVE = 10
MESSAGE_DATE_RESERVES = "Debe haber al menos 1 hora de diferencia, no más de 14 días"
MESSAGE_TIME_RESERVES = "De 12:00 a 23:30"
MESSAGE_ERROR_DATE_RESERVES = "Elige una fecha válida, debe haber al menos 1 hora de diferencia, no más de 14 días, de 12:00 a 23:30"


PAGINATOR_PER_PAGE = 10

URL_INDEX = "inicio/"
URL_DISHES = "platos/"
URL_DISH = "plato/"
URL_MENUS = "menus/"
URL_MENU = "menu/"
URL_RESERVE = "reservas/"
URL_CONTACT = "contacto/"
URL_DATA_RESERVES = "proximas_reservas/"