# Generated by Django 3.2.18 on 2023-05-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('main_phone', models.CharField(max_length=15)),
                ('main_email', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('pk_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('pk_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('date_utc', models.DateTimeField(verbose_name='date reserve UTC')),
                ('number_people', models.IntegerField(default=1)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('other', models.CharField(blank=True, max_length=200)),
                ('fk_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Reserve',
            },
        ),
        migrations.CreateModel(
            name='Contact_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('fk_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.contact')),
            ],
            options={
                'verbose_name_plural': 'Contact_Phone',
            },
        ),
        migrations.CreateModel(
            name='Contact_Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('fk_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.contact')),
            ],
            options={
                'verbose_name_plural': 'Contact_Mail',
            },
        ),
        migrations.AddConstraint(
            model_name='contact_phone',
            constraint=models.UniqueConstraint(fields=('fk_contact', 'phone'), name='unique_fk_contact_phone_combination'),
        ),
        migrations.AddConstraint(
            model_name='contact_mail',
            constraint=models.UniqueConstraint(fields=('fk_contact', 'email'), name='unique_fk_contact_email_combination'),
        ),
    ]
