# Generated by Django 3.2.18 on 2023-04-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_phone', models.CharField(max_length=15)),
                ('main_email', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('name_dish', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('src_photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name_restaurant', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_people', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
                ('name_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(max_length=200)),
                ('name_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.CharField(max_length=15)),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.contact')),
            ],
        ),
    ]
