# Generated by Django 3.2.18 on 2023-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='popular',
            field=models.IntegerField(default=0),
        ),
    ]
