# Generated by Django 3.2.18 on 2023-05-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('pk_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('src_photo', models.ImageField(default='no_image.jpg', upload_to='')),
                ('popular', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Dish',
            },
        ),
        migrations.CreateModel(
            name='Dish_category',
            fields=[
                ('pk_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Dish_category',
            },
        ),
        migrations.CreateModel(
            name='Dish_type',
            fields=[
                ('pk_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Dish_type',
            },
        ),
        migrations.CreateModel(
            name='Menu_Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.dish')),
                ('fk_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu_Dish',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='fk_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.dish_category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='fk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.dish_type'),
        ),
        migrations.AddConstraint(
            model_name='menu_dish',
            constraint=models.UniqueConstraint(fields=('fk_menu', 'fk_dish'), name='unique_fk_menu_fk_dish_combination'),
        ),
    ]
