# Generated by Django 3.2.18 on 2023-05-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0002_auto_20230510_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contact_mail',
            options={'verbose_name_plural': 'Contact_Mails'},
        ),
        migrations.AlterModelOptions(
            name='contact_phone',
            options={'verbose_name_plural': 'Contact_Phones'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dish_category',
            options={'verbose_name_plural': 'Dish_categories'},
        ),
        migrations.AlterModelOptions(
            name='dish_type',
            options={'verbose_name_plural': 'Dish_types'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menu_dish',
            options={'verbose_name_plural': 'Menu_Dishes'},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name_plural': 'Reserves'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='main_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='other',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
