# Generated by Django 3.2.18 on 2023-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0002_dish_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='src_photo',
            field=models.ImageField(default='img/no_image.jpg', upload_to=''),
        ),
    ]
