# Generated by Django 3.2.18 on 2023-04-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0002_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(max_length=200)),
                ('name_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.dish')),
            ],
        ),
    ]
