# Generated by Django 3.2.18 on 2023-04-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0003_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_Dish',
        ),
    ]
