# Generated by Django 3.2.18 on 2023-04-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0004_rename_menu_menu_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='menu_dish',
            name='name_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.menu'),
        ),
    ]
