# Generated by Django 3.2.18 on 2023-04-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0004_alter_dish_src_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
