# Generated by Django 3.2.18 on 2023-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0004_dish_type_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_category',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
