# Generated by Django 3.2.18 on 2023-04-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0005_delete_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('date_utc', models.DateTimeField()),
                ('number_people', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
                ('name_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.restaurant')),
            ],
        ),
    ]
