# Generated by Django 4.1.5 on 2023-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0006_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
