# Generated by Django 3.2.18 on 2023-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0006_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='id',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='name_restaurant',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
