# Generated by Django 3.2.18 on 2023-04-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0008_remove_reserve_date_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='number_people',
        ),
    ]
