# Generated by Django 3.2.18 on 2023-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0010_delete_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('name_restaurant', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
            ],
        ),
    ]
