# Generated by Django 3.2.18 on 2023-04-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0012_reserve_date_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date_utc',
        ),
    ]
