# Generated by Django 3.2.18 on 2023-04-08 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0013_remove_reserve_date_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='date_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
