# Generated by Django 3.2.18 on 2023-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0014_reserve_date_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date_utc',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
