# Generated by Django 3.2.18 on 2023-04-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0017_auto_20230408_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='name_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restChifa.restaurant'),
        ),
    ]
