# Generated by Django 3.2.18 on 2023-04-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0018_alter_reserve_name_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
