# Generated by Django 3.2.18 on 2023-04-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0020_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
