# Generated by Django 3.2.18 on 2023-04-23 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restChifa', '0022_auto_20230422_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_utc',
            field=models.DateTimeField(verbose_name='date reserve UTC'),
        ),
    ]
